Test run simple test.

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -4,6 +4,8 @@ on: workflow_dispatch
 jobs:
   Explore-GitHub-Actions:
     runs-on: ubuntu-20.04
+    env:
+      Repo_Name: ${{ github.event.repository.name }}
     permissions:
       checks: write
     steps:
@@ -13,41 +15,28 @@ jobs:
         run: |
           echo "${{ secrets.AWS_EC2_INSTANCE_SSH_PRIVATE_KEY }}" >> ~/aws_ec2_key.pem
           chmod 400 ~/aws_ec2_key.pem
-          scp -o StrictHostKeyChecking=no -i ~/aws_ec2_key.pem README.md ec2-user@ec2-18-237-84-202.us-west-2.compute.amazonaws.com:~/
+          scp -r -o StrictHostKeyChecking=no -i ~/aws_ec2_key.pem ../ ec2-user@ec2-18-237-84-202.us-west-2.compute.amazonaws.com:~/$Repo_Name
 
-      # - name: Deploy to ec2
-      #   uses: easingthemes/ssh-deploy@main
-      #   env:
-      #     SSH_PRIVATE_KEY: ${{ secrets.AWS_EC2_INSTANCE_SSH_PRIVATE_KEY }}
-      #     SSH_CMD_ARGS: "-o StrictHostKeyChecking=no"
-      #     REMOTE_HOST: ec2-18-237-84-202.us-west-2.compute.amazonaws.com
-      #     REMOTE_USER: ec2-user
-      #     ARGS: "-rlgoDc -i -q"
-      #     SOURCE: ""
-      #     TARGET: /home/ec2-user/${{ github.event.repository.name }}/
-      #     EXCLUDE: ".git/, .github/"
-      #     SCRIPT_BEFORE: |
-      #       whoami
-      #     SCRIPT_AFTER: |
-      #       whoami
-      #       ls -al
-      #       echo $RSYNC_STDOUT
-      #       cd my-demo
-      #       sh ./run_e2e_testing.sh
+      - run: pip install --no-cache-dir -q -r requirements.txt --use-pep517
+      - run: pytest --html=outputs/test_report.html --self-contained-html --junitxml=outputs/test_report.xml test_1.py 
 
-      # - name: Upload test result
-      #   if: ${{ always() }}
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: test-report
-      #     path: outputs/
-      #     retention-days: 30
-      # - name: Test Report
-      #   uses: dorny/test-reporter@v1
-      #   if: success() || failure()    # run this step even if previous step failed
-      #   with:
-      #     name: Pytest Tests            # Name of the check run which will be created
-      #     path: outputs/test_report.xml    # Path to test results
-      #     reporter: java-junit        # Format of test results
+      - name: copy outputs
+        run: |
+          scp -r -o StrictHostKeyChecking=no -i ~/aws_ec2_key.pem ec2-user@ec2-18-237-84-202.us-west-2.compute.amazonaws.com:~/$Repo_Name/outputs/ outputs/
+
+      - name: Upload test result
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v3
+        with:
+          name: test-report
+          path: outputs/
+          retention-days: 30
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Pytest Tests            # Name of the check run which will be created
+          path: outputs/test_report.xml    # Path to test results
+          reporter: java-junit        # Format of test results
 
       - run: echo "🍏 This job's status is ${{ job.status }}."
